### ISSUE TITLE
Nitrogen Distiller not working

### ISSUE THREAD

**Issue by LarrytheTurtle23** [Arth0x/AetherUnbound#5]
I tried supplying with water using an efflux pump, no work. I loaded up a sandbox and supplied with water, nitrogen, liquid nitrogen and every item in the game, no work. The block won't even show any liquid inside, even though the conduits are placed properly. Is this a bug, or am I just stupid?
![Screen Shot 2024-01-05 at 5 03 00 PM](https://github.com/Arth0x/Mindustrinity/assets/62360353/57d323e9-ac0f-4493-9487-23de6c5b735c)

**Comment by LarrytheTurtle23** [comment]
wait sorry wrong mod ignore this

**Comment by ZaharitIngot** [comment]
you need multicraft lib, but i think you already know in such a big time
